# Sequence Blocks

In [28]:
chars =  list("abcdefghijklmnopqrstuvwxyz -_,")
ctoi = {c: i for i, c in enumerate(chars)}
itoc = {i:c for c, i in ctoi.items()}


In [29]:
import torch

In [30]:
text = "hello world, this is Bread Modular".lower()
text

'hello world, this is bread modular'

In [31]:
# convert the text into a pytorch list
data = torch.tensor([ctoi[c] for c in text], dtype=torch.long)
data

tensor([ 7,  4, 11, 11, 14, 26, 22, 14, 17, 11,  3, 29, 26, 19,  7,  8, 18, 26,
         8, 18, 26,  1, 17,  4,  0,  3, 26, 12, 14,  3, 20, 11,  0, 17])

In [32]:
# LLM usually work with blocks. Here use 8
## GPT3 seems to be use 2048
block_size = 8

In [33]:
i = torch.randint(len(data) - block_size - 1, (1,))
x = data[i: i+block_size]
y = data[i + 1: i + 1 + block_size]
x, y

(tensor([ 8, 18, 26,  8, 18, 26,  1, 17]),
 tensor([18, 26,  8, 18, 26,  1, 17,  4]))

In [34]:
def get_batch(d):
    i = torch.randint(len(d) - block_size - 1, (1,))
    x = data[i : i + block_size]
    y = data[i + 1 : i + 1 + block_size]
    return x, y

In [35]:
get_batch(data)

(tensor([26,  8, 18, 26,  1, 17,  4,  0]),
 tensor([ 8, 18, 26,  1, 17,  4,  0,  3]))

## Notes

Here we trying to get training data. The whole idea of a LLM is to predit the next word. In our case, we are trying to predict the next letter.

So, this is we are building the training dataset for that.